export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_APPLY_DOCTOR_REQUEST = 'USER_APPLY_DOCTOR_REQUEST';
export const USER_APPLY_DOCTOR_SUCCESS = 'USER_APPLY_DOCTOR_SUCCESS';
export const USER_APPLY_DOCTOR_FAIL = 'USER_APPLY_DOCTOR_FAIL';

export const CLEAR_NOTIFICATIONS_REQUEST = 'CLEAR_NOTIFICATIONS_REQUEST';
export const CLEAR_NOTIFICATIONS_SUCCESS = 'CLEAR_NOTIFICATIONS_SUCCESS';
export const CLEAR_NOTIFICATIONS_FAIL = 'CLEAR_NOTIFICATIONS_FAIL';

export const MARK_ALL_NOTIFICATIONS_AS_SEEN_REQUEST =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_REQUEST';
export const MARK_ALL_NOTIFICATIONS_AS_SEEN_SUCCESS =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_AS_SEEN_FAIL =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_RESET = 'USER_RESET';

export const DOCTOR_UPDATE_REQUEST = 'DOCTOR_UPDATE_REQUEST';
export const DOCTOR_UPDATE_SUCCESS = 'DOCTOR_UPDATE_SUCCESS';
export const DOCTOR_UPDATE_FAIL = 'DOCTOR_UPDATE_FAIL';

export const DOCTOR_DELETE_REQUEST = 'DOCTOR_DELETE_REQUEST';
export const DOCTOR_DELETE_SUCCESS = 'DOCTOR_DELETE_SUCCESS';
export const DOCTOR_DELETE_FAIL = 'DOCTOR_DELETE_FAIL';

export const DOCTOR_DETAILS_REQUEST = 'DOCTOR_DETAILS_REQUEST';
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS';
export const DOCTOR_DETAILS_FAIL = 'DOCTOR_DETAILS_FAIL';

export const DOCTORS_REQUEST = 'DOCTORS_REQUEST';
export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
export const DOCTORS_FAIL = 'DOCTORS_FAIL';
