export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_APPLY_DOCTOR_REQUEST = 'USER_APPLY_DOCTOR_REQUEST';
export const USER_APPLY_DOCTOR_SUCCESS = 'USER_APPLY_DOCTOR_SUCCESS';
export const USER_APPLY_DOCTOR_FAIL = 'USER_APPLY_DOCTOR_FAIL';

export const CLEAR_NOTIFICATIONS_REQUEST = 'CLEAR_NOTIFICATIONS_REQUEST';
export const CLEAR_NOTIFICATIONS_SUCCESS = 'CLEAR_NOTIFICATIONS_SUCCESS';
export const CLEAR_NOTIFICATIONS_FAIL = 'CLEAR_NOTIFICATIONS_FAIL';

export const MARK_ALL_NOTIFICATIONS_AS_SEEN_REQUEST =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_REQUEST';
export const MARK_ALL_NOTIFICATIONS_AS_SEEN_SUCCESS =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_AS_SEEN_FAIL =
  'MARK_ALL_NOTIFICATIONS_AS_SEEN_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_RESET = 'USER_RESET';
